/**
 * Replays Solidity-generated RoycoDayAccountant vectors through the public Day
 * WAD engine. The immutable source vectors were generated by
 * lib/try/harness/VectorGen.t.sol against the compiled Royco Day contracts.
 */
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  coverageUtilizationWad,
  liquidityUtilizationWad,
  newMarket,
  postOpAccountingWad,
  reconcile,
  selfLiquidationClaimWad,
  sharesForValueWad,
  ydmShareWad,
} from './engine';
import { defaultConfig } from './runner';
import type { LiveState, MarketConfig } from './types';
import { mulDiv, Rounding, saturatingSub, UINT256_MAX, WAD } from './wad';

interface Vector {
  group: string;
  label: string;
  inputs: { stRaw?: string; jtRaw?: string; priceWad?: string; dtSec?: string };
  outputs: {
    value?: string;
    stEff?: string;
    jtEff?: string;
    il?: string;
    coverageUtilWad?: string;
    marketState?: string;
  };
}

interface CoreBundle {
  schemaVersion: number;
  provenance: {
    repository: string;
    commit: string;
    solc: string;
    harness: string;
    harnessSha256: string;
    generator: string;
  };
  requiredGroups: string[];
  vectors: Vector[];
}

const here = dirname(fileURLToPath(import.meta.url));
const corePath = join(here, 'vectors/core.golden.json');
const core = JSON.parse(readFileSync(corePath, 'utf8')) as CoreBundle;
const vectors = core.vectors;
const byLabel = new Map(vectors.map((vector) => [vector.label, vector]));
const rows: Array<{ group: string; label: string; failures: string[] }> = [];

const config: MarketConfig = defaultConfig({
  coverage: 0.3,
  beta: 1,
  targetUtilization: 0.9,
  liquidationUtilization: 2,
  fixedTermDurationSec: 2_592_000,
  stProtocolFee: 0,
  jtProtocolFee: 0,
  yieldShareProtocolFee: 0,
  ltYieldShareProtocolFee: 0,
  riskYDM: { mode: 'static', y0: 0.53, yTarget: 0.53, y100: 0.53 },
  maxJTYieldShare: 1,
  minLiquidity: 0,
  liqYDM: { mode: 'static', y0: 0, yTarget: 0, y100: 0 },
  maxLTYieldShare: 0,
  dustTolerance: 0,
});

const fresh = (): LiveState => newMarket(config, { st: 1_000, jt: 500, lt: 0 });
const rawForPrice = (priceWad: bigint, capital: bigint) => capital * priceWad;

function compareScalar(label: string, actual: bigint): void {
  const vector = byLabel.get(label);
  if (!vector?.outputs.value) throw new Error(`missing scalar vector ${label}`);
  const expected = BigInt(vector.outputs.value);
  rows.push({
    group: vector.group,
    label,
    failures: actual === expected ? [] : [`value got ${actual}, expected ${expected}`],
  });
}

function step(state: LiveState, label: string, priceWad: bigint, dt: bigint): void {
  state.t += dt;
  reconcile(state, config, rawForPrice(priceWad, 1_000n), rawForPrice(priceWad, 500n));
  const vector = byLabel.get(label);
  if (!vector) throw new Error(`missing sync vector ${label}`);
  const failures: string[] = [];
  const compare = (field: string, actual: bigint, expected?: string) => {
    if (expected === undefined) return;
    if (actual !== BigInt(expected)) failures.push(`${field} got ${actual}, expected ${expected}`);
  };
  compare('stEff', state.stEffectiveNAV, vector.outputs.stEff);
  compare('jtEff', state.jtEffectiveNAV, vector.outputs.jtEff);
  compare('il', state.jtImpermanentLoss, vector.outputs.il);
  compare(
    'coverageUtilWad',
    coverageUtilizationWad(state.stRawNAV, state.jtRawNAV, 1, 300000000000000000n, state.jtEffectiveNAV),
    vector.outputs.coverageUtilWad,
  );
  if (state.marketState !== vector.outputs.marketState) {
    failures.push(`marketState got ${state.marketState}, expected ${vector.outputs.marketState}`);
  }
  rows.push({ group: vector.group, label, failures });
}

for (const utilization of [
  0n,
  450000000000000000n,
  900000000000000000n,
  950000000000000000n,
  WAD,
  1500000000000000000n,
]) {
  compareScalar(
    `ydm_U_${utilization}`,
    ydmShareWad(config.riskYDM, 530000000000000000n, utilization, 900000000000000000n),
  );
}

compareScalar('cov_1000_500_500', coverageUtilizationWad(1000n * WAD, 500n * WAD, 1, 300000000000000000n, 500n * WAD));
compareScalar('cov_700_300_300', coverageUtilizationWad(700n * WAD, 300n * WAD, 1, 300000000000000000n, 300n * WAD));
compareScalar('cov_minCov0', coverageUtilizationWad(1000n * WAD, 500n * WAD, 1, 0n, 500n * WAD));
compareScalar('cov_jtEff0_exposure', coverageUtilizationWad(1000n * WAD, 500n * WAD, 1, 300000000000000000n, 0n));
compareScalar('cov_zero_exposure', coverageUtilizationWad(0n, 0n, 1, 300000000000000000n, 1n));

const DAY = 86_400n;
const single = (label: string, price: bigint, dt: bigint) => step(fresh(), label, price, dt);
single('C0_genesis', WAD, 0n);
single('C1_flat_30d', WAD, 30n * DAY);
single('C2_up10_30d', 1100000000000000000n, 30n * DAY);
single('C3_down10_30d', 900000000000000000n, 30n * DAY);
{
  const state = fresh();
  step(state, 'C4_down10_30d', 900000000000000000n, 30n * DAY);
  step(state, 'C4_recover95_5d', 950000000000000000n, 5n * DAY);
}
single('C6_down60_30d', 400000000000000000n, 30n * DAY);
{
  const state = fresh();
  step(state, 'C7_down10_30d', 900000000000000000n, 30n * DAY);
  step(state, 'C7_termElapsed_flat', 900000000000000000n, 31n * DAY);
}
{
  const state = fresh();
  const prices = [
    1000000000000000000n, 1020000000000000000n, 1050000000000000000n,
    1030000000000000000n, 1080000000000000000n, 980000000000000000n,
    950000000000000000n, 1010000000000000000n, 1060000000000000000n,
    1100000000000000000n, 1040000000000000000n, 1120000000000000000n,
  ];
  prices.forEach((price, index) => step(state, `D_step_${index + 1}`, price, 30n * DAY));
}
{
  const state = fresh();
  step(state, 'C5_down10_30d', 900000000000000000n, 30n * DAY);
  step(state, 'C5_recover105_5d', 1050000000000000000n, 5n * DAY);
}

const TERM = 2_592_000n;
{
  const state = fresh();
  step(state, 'E1_enter_down10', 900000000000000000n, TERM);
  for (let i = 1; i <= 5; i += 1) step(state, `E1_flat_${i}`, 900000000000000000n, TERM);
}
for (const [prefix, dt] of [
  ['E2', TERM - 1n],
  ['E3', TERM],
  ['E4', TERM + 1n],
] as const) {
  const state = fresh();
  step(state, `${prefix}_enter_down10`, 900000000000000000n, TERM);
  step(state, `${prefix}_${prefix === 'E2' ? 'before_end' : prefix === 'E3' ? 'at_end' : 'after_end'}`, 900000000000000000n, dt);
}
{
  const state = fresh();
  step(state, 'E5_enter_down10', 900000000000000000n, TERM);
  step(state, 'E5_partial_1e6', 900000000000000000n, 1_000_000n);
  step(state, 'E5_partial_2e6', 900000000000000000n, 2_000_000n);
}
{
  const state = fresh();
  step(state, 'E6_enter_down10', 900000000000000000n, TERM);
  step(state, 'E6_recover110', 1100000000000000000n, TERM - 1n);
  step(state, 'E6_reenter_down10', 900000000000000000n, 100n);
}

type ExtendedFields = Record<string, string | boolean>;
interface ExtendedVector {
  id: string;
  group: string;
  kind: string;
  inputs: ExtendedFields;
  outputs: ExtendedFields;
}
interface ExtendedBundle {
  schemaVersion: number;
  provenance: {
    repository: string;
    commit: string;
    solc: string;
    harness: string;
    harnessSha256: string;
    generator: string;
  };
  requiredGroups: string[];
  vectors: ExtendedVector[];
}

const extendedPath = join(here, 'vectors/golden.json');
const lock = JSON.parse(readFileSync(join(here, 'vectors/contract-lock.json'), 'utf8')) as {
  commit: string;
  schemaVersion: number;
};
const extended = JSON.parse(readFileSync(extendedPath, 'utf8')) as ExtendedBundle;
if (core.schemaVersion !== lock.schemaVersion) throw new Error('Day core Solidity vector schema version does not match the contract lock');
if (extended.schemaVersion !== lock.schemaVersion) throw new Error('Day Solidity vector schema version does not match the contract lock');
if (core.provenance.commit !== lock.commit) throw new Error('Day core Solidity vectors were not generated from the pinned royco-day commit');
if (extended.provenance.commit !== lock.commit) throw new Error('Day Solidity vectors were not generated from the pinned royco-day commit');
const harnessHash = createHash('sha256')
  .update(readFileSync(join(here, 'harness/DayVectorGen.t.sol')))
  .digest('hex');
if (harnessHash !== core.provenance.harnessSha256) throw new Error('Day core Solidity vector harness hash does not match provenance');
if (harnessHash !== extended.provenance.harnessSha256) throw new Error('Day Solidity vector harness hash does not match provenance');
const coreGroups = new Set(core.vectors.map((vector) => vector.group));
for (const group of core.requiredGroups) {
  if (!coreGroups.has(group)) throw new Error(`missing required Day core Solidity vector group: ${group}`);
}
const extendedGroups = new Set(extended.vectors.map((vector) => vector.group));
for (const group of extended.requiredGroups) {
  if (!extendedGroups.has(group)) throw new Error(`missing required Day Solidity vector group: ${group}`);
}
const ids = new Set<string>();
const bigintField = (fields: ExtendedFields, name: string): bigint => {
  const value = fields[name];
  if (typeof value !== 'string' || !/^\d+$/.test(value)) throw new Error(`${name} must be an unsigned decimal string`);
  return BigInt(value);
};
const compareExtended = (vector: ExtendedVector, actual: Record<string, bigint | string | boolean>) => {
  const failures: string[] = [];
  for (const [field, expected] of Object.entries(vector.outputs)) {
    const got = actual[field];
    if (got === undefined) failures.push(`${field} was not replayed`);
    else if (typeof got === 'bigint' ? got !== BigInt(String(expected)) : got !== expected) {
      failures.push(`${field} got ${String(got)}, expected ${String(expected)}`);
    }
  }
  rows.push({ group: vector.group, label: vector.id, failures });
};

for (const vector of extended.vectors) {
  if (ids.has(vector.id)) throw new Error(`duplicate Day Solidity vector id: ${vector.id}`);
  ids.add(vector.id);
  if (vector.kind === 'liquidityUtilization') {
    compareExtended(vector, {
      value: liquidityUtilizationWad(
        bigintField(vector.inputs, 'stEffective'),
        bigintField(vector.inputs, 'minLiquidityWAD'),
        bigintField(vector.inputs, 'ltRaw'),
      ),
    });
  } else if (vector.kind === 'sharesForValue') {
    compareExtended(vector, {
      shares: sharesForValueWad(
        bigintField(vector.inputs, 'value'),
        bigintField(vector.inputs, 'totalValue'),
        bigintField(vector.inputs, 'supply'),
      ),
    });
  } else if (vector.kind === 'feePremiumShares') {
    const premium = bigintField(vector.inputs, 'premium');
    const stFee = bigintField(vector.inputs, 'stFee');
    const lptFee = bigintField(vector.inputs, 'lptFee');
    const retained = bigintField(vector.inputs, 'stEffective') - premium - stFee;
    const supply = bigintField(vector.inputs, 'supply');
    const premiumShares = sharesForValueWad(saturatingSub(premium, lptFee), retained, supply);
    const feeShares = sharesForValueWad(stFee + lptFee, retained, supply);
    compareExtended(vector, { premiumShares, feeShares, supplyAfter: supply + premiumShares + feeShares });
  } else if (vector.kind === 'accountantSync') {
    const fee = (name: string) => vector.inputs[name] === undefined ? 100000000000000000n : bigintField(vector.inputs, name);
    const cfg = defaultConfig({
      coverage: 0.1,
      beta: 1,
      targetUtilization: 0.9,
      liquidationUtilization: 1.1,
      minLiquidity: 0.05,
      liqTargetUtilization: 0.9,
      fixedTermDurationSec: 604800,
      stProtocolFee: Number(fee('stFeeRate')) / 1e18,
      jtProtocolFee: Number(fee('jtFeeRate')) / 1e18,
      yieldShareProtocolFee: Number(fee('jtShareFeeRate')) / 1e18,
      ltYieldShareProtocolFee: Number(fee('ltShareFeeRate')) / 1e18,
      riskYDM: { mode: 'static', y0: 0.2, yTarget: 0.2, y100: 0.2 },
      maxJTYieldShare: 0.2,
      liqYDM: { mode: 'static', y0: 0.1, yTarget: 0.1, y100: 0.1 },
      maxLTYieldShare: 0.1,
      dustTolerance: 0,
    });
    const state = newMarket(cfg, { st: 1000, jt: 200, lt: 100 });
    state.t = bigintField(vector.inputs, 'elapsed');
    const result = reconcile(state, cfg, bigintField(vector.inputs, 'newST'), bigintField(vector.inputs, 'newJT'));
    compareExtended(vector, {
      marketState: state.marketState,
      stRaw: state.stRawNAV,
      jtRaw: state.jtRawNAV,
      ltRaw: 0n,
      stEffective: state.stEffectiveNAV,
      jtEffective: state.jtEffectiveNAV,
      jtIL: state.jtImpermanentLoss,
      liquidityPremium: result.contractValues.liquidityPremium,
      stFee: result.contractValues.stProtocolFee,
      jtFee: result.contractValues.jtProtocolFee,
      ltFee: result.contractValues.ltProtocolFee,
      coverageUtilWAD: coverageUtilizationWad(state.stRawNAV, state.jtRawNAV, 1, 100000000000000000n, state.jtEffectiveNAV),
      liquidityUtilWAD: 0n,
    });
  } else if (vector.kind === 'ltCommit') {
    compareExtended(vector, { lastLTRawNAV: bigintField(vector.inputs, 'ltRaw') });
  } else if (vector.kind === 'maxSTDeposit') {
    const collateral = bigintField(vector.inputs, 'collateral');
    const stEffective = bigintField(vector.inputs, 'stEffective');
    const jtEffective = bigintField(vector.inputs, 'jtEffective');
    const lptRaw = bigintField(vector.inputs, 'lptRaw');
    const minCoverageWAD = bigintField(vector.inputs, 'minCoverageWAD');
    const minLiquidityWAD = bigintField(vector.inputs, 'minLiquidityWAD');
    const dust = bigintField(vector.inputs, 'dust');
    const coverageBound = minCoverageWAD === 0n
      ? UINT256_MAX
      : saturatingSub(mulDiv(jtEffective, WAD, minCoverageWAD), collateral + dust);
    const liquidityBound = minLiquidityWAD === 0n
      ? UINT256_MAX
      : saturatingSub(mulDiv(lptRaw, WAD, minLiquidityWAD), stEffective + dust);
    compareExtended(vector, { max: coverageBound < liquidityBound ? coverageBound : liquidityBound });
  } else if (vector.kind === 'maxLPTWithdrawal') {
    const lptRaw = bigintField(vector.inputs, 'lptRaw');
    const minLiquidityWAD = bigintField(vector.inputs, 'minLiquidityWAD');
    const required = mulDiv(
      bigintField(vector.inputs, 'stEffective') + bigintField(vector.inputs, 'dust'),
      minLiquidityWAD,
      WAD,
      Rounding.Ceil,
    );
    compareExtended(vector, { max: saturatingSub(lptRaw, required) });
  } else if (vector.kind === 'postOp' || vector.kind === 'postOpRevert') {
    const seedST = bigintField(vector.inputs, 'seedST');
    const seedJT = bigintField(vector.inputs, 'seedJT');
    const seedLT = bigintField(vector.inputs, 'seedLT');
    const operation = String(vector.inputs.operation) as Parameters<typeof postOpAccountingWad>[2]['operation'];
    try {
      const actual = postOpAccountingWad(
        { stRawNAV: seedST, jtRawNAV: seedJT, stEffectiveNAV: seedST, jtEffectiveNAV: seedJT, jtImpermanentLoss: 0n },
        { beta: 1, coverage: 0.1, minLiquidity: 0.05, liquidationUtilization: 1.1 },
        {
          operation,
          stRaw: bigintField(vector.inputs, 'stRaw'),
          jtRaw: bigintField(vector.inputs, 'jtRaw'),
          ltRaw: bigintField(vector.inputs, 'ltRaw'),
          previousLTRaw: seedLT,
          bonus: bigintField(vector.inputs, 'bonus'),
          enforce: true,
        },
      );
      compareExtended(vector, vector.kind === 'postOpRevert' ? { reverted: false, selector: 0n } : {
        marketState: 'PERPETUAL',
        ...actual,
        liquidityPremium: 0n,
        stFee: 0n,
        jtFee: 0n,
        ltFee: 0n,
      });
    } catch (error) {
      const selectorByError: Record<string, bigint> = {
        COVERAGE_REQUIREMENT_VIOLATED: 1887653499n,
        LIQUIDITY_REQUIREMENT_VIOLATED: 422986096n,
      };
      const message = error instanceof Error ? error.message : String(error);
      compareExtended(vector, { reverted: true, selector: selectorByError[message] ?? 0n });
    }
  } else if (vector.kind === 'premiumStaging') {
    const stEffective = bigintField(vector.inputs, 'stEffective');
    const premium = bigintField(vector.inputs, 'premium');
    const stFee = bigintField(vector.inputs, 'stFee');
    const jtFee = bigintField(vector.inputs, 'jtFee');
    const ltFee = bigintField(vector.inputs, 'ltFee');
    const stSupply = bigintField(vector.inputs, 'stSupply');
    const jtSupply = bigintField(vector.inputs, 'jtSupply');
    const ltSupply = bigintField(vector.inputs, 'ltSupply');
    const premiumShares = sharesForValueWad(saturatingSub(premium, ltFee), stEffective - premium - stFee, stSupply);
    const stFeeShares = sharesForValueWad(stFee + ltFee, stEffective - premium - stFee, stSupply);
    const stSupplyAfter = stSupply + premiumShares + stFeeShares;
    const jtFeeShares = sharesForValueWad(jtFee, bigintField(vector.inputs, 'jtEffective') - jtFee, jtSupply);
    compareExtended(vector, {
      stSupplyAfter,
      jtSupplyAfter: jtSupply + jtFeeShares,
      ltSupplyAfter: ltSupply,
      premiumShares,
      stFeeShares,
      jtFeeShares,
      ltFeeShares: 0n,
      idlePremiumShares: premiumShares,
    });
  } else if (vector.kind === 'selfLiquidation') {
    const result = selfLiquidationClaimWad({
      bonusWAD: bigintField(vector.inputs, 'bonusWAD'),
      stEffective: bigintField(vector.inputs, 'stEffective'),
      jtEffective: bigintField(vector.inputs, 'jtEffective'),
      coverageUtilWAD: bigintField(vector.inputs, 'coverageUtilWAD'),
      liquidationUtilWAD: bigintField(vector.inputs, 'liquidationUtilWAD'),
      claimCollateral: bigintField(vector.inputs, 'claimCollateral'),
      claimNAV: bigintField(vector.inputs, 'claimNAV'),
    });
    compareExtended(vector, {
      bonus: result.bonus,
      claimCollateral: result.claimCollateral,
      claimNAV: result.claimNAV,
    });
  } else {
    throw new Error(`unsupported Day Solidity vector kind: ${vector.kind}`);
  }
}

const ordered = rows.sort((a, b) => a.group.localeCompare(b.group));
for (const row of ordered) {
  console.log(`${row.failures.length === 0 ? 'PASS' : 'FAIL'} ${row.group} / ${row.label}`);
  row.failures.forEach((failure) => console.log(`  ${failure}`));
}
const passed = rows.filter((row) => row.failures.length === 0).length;
console.log(`\n${passed}/${rows.length} Day Solidity WAD vectors PASS (${vectors.length} core + ${extended.vectors.length} extended)`);
if (passed !== rows.length) process.exitCode = 1;

// Guard the UINT256 sentinel explicitly; it is easy to accidentally coerce it.
if (coverageUtilizationWad(WAD, WAD, 1, WAD, 0n) !== UINT256_MAX) process.exitCode = 1;
