// Turns a derived manifest into the exact files and commands a maintainer runs
// to publish the pool as a simulator page.

import type { DayMarketManifest, DaySeriesPoint } from "@/lib/day-simulator-template/market";
import { marketModuleSource, routeSource } from "@/lib/pool-creator/derive";

export type ExportFile = { path: string; contents: string };

export function exportFiles(
  manifest: DayMarketManifest,
  series: DaySeriesPoint[],
): ExportFile[] {
  const dir = `lib/day-markets/${manifest.id}`;
  return [
    { path: `${dir}/market.json`, contents: `${JSON.stringify(manifest, null, 2)}\n` },
    { path: `${dir}/series.json`, contents: `${JSON.stringify(series, null, 2)}\n` },
    { path: `${dir}/market.ts`, contents: marketModuleSource() },
    { path: `app${manifest.route}/page.tsx`, contents: routeSource(manifest.id, manifest) },
  ];
}

/** The three commands that take these files from "downloaded" to "certified". */
export function publishCommands(id: string): string[] {
  return [
    `npm run day-sim:verify -- ${id}`,
    `npm run day-sim:calibrate -- ${id}`,
    `npm run day-sim:certify -- ${id}`,
  ];
}

/** A single copyable bundle, for handing to someone who will apply it. */
export function bundleText(manifest: DayMarketManifest, series: DaySeriesPoint[]): string {
  const files = exportFiles(manifest, series);
  const header = [
    `# Royco Day market: ${manifest.identity.marketName}`,
    `# id: ${manifest.id}   route: ${manifest.route}`,
    `# Generated by /create. Apply these files, then run:`,
    ...publishCommands(manifest.id).map((command) => `#   ${command}`),
    "",
  ].join("\n");

  return (
    header +
    files
      .map((file) => `# ─── ${file.path} ${"─".repeat(Math.max(0, 60 - file.path.length))}\n${file.contents}`)
      .join("\n")
  );
}

/** Trigger a client-side download without leaving the page. */
export function downloadFile(filename: string, contents: string, mime = "application/json"): void {
  if (typeof document === "undefined") return;
  const blob = new Blob([contents], { type: mime });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}
